# This is a basic workflow to help you get started with Actions

name: Bump and build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   bump:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # Fetch code
        with:
          ref: ${{ github.ref }}
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
   
   publish:
      name: Publish Docker image
      needs: bump
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - run: npm ci

        - run: echo "::set-env name=RELEASE_VERSION::$(jq -r .version package.json)"

        - name: Publish Docker image
          uses: elgohr/Publish-Docker-Github-Action@2.12
          with:
            # The name of the image you would like to push
            name: oslokommune/king-kong-ping-pong/king-kong-ping-pong
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            tags: latest,${{ env.RELEASE_VERSION }}
